---
metallb:
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses: 192.168.0.240-192.168.0.250

ingress-nginx:
  controller:
    service:
      externalIPs: []

cert-manager:
  installCRDs: true
