---
kafka:
  cp-zookeeper:
    servers: 1
    persistence:
      enabled: true
      dataDirSize: 1Gi
      dataLogDirSize: 4Gi
  cp-kafka:
    brokers: 5
    persistence:
      enabled: true
      size: 32Gi
      disksPerBroker: 1
    prometheus:
      jmx:
        enabled: false
    nodeport:
      enabled: true
      servicePort: 19092
      firstListenerPort: 31090

ingress:
  host: ""
