---
kibana:
  elasticsearchHosts: "http://elasticsearch.data-elastic.svc:9200"
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

oauth2-proxy:
  config:
    existingSecret: kibana-oauth2-secret
    # https://oauth2-proxy.github.io/oauth2-proxy/configuration#config-file
    # https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "http://observer-kibana-kibana:5601" ]
      provider = "github"
  image:
    tag: v6.1.1
  extraEnv:
  - name:  OAUTH2_PROXY_GITHUB_ORG
    value: ""
  ingress:
    enabled: true
    hosts:
    - ""
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    tls:
    - secretName: kibana-oauth2-proxy-tls
      hosts:
      - ""
