---
influxdb:
  persistence:
    enabled: true
    existingClaim: ""
  setDefaultUser:
    enabled: true
    user:
      existingSecret: influxdb-auth-secret
  podAnnotations:
    co.elastic.logs/enabled: "true"
    co.elastic.logs/fileset.stdout: access
    co.elastic.logs/fileset.stderr: error
    co.elastic.logs/exclude_lines: '[ "GET /ping" ]'
  ingress:
    enabled: true
    hostname: ""
  config:
    http:
      auth-enabled: true
      ping-auth-enabled: false
  initScripts:
    enabled: true
