---
namespace: data-influxdb

influxdb:
  persistence:
    enabled: true
    existingClaim: ""
  setDefaultUser:
    enabled: true
    user:
      existingSecret: influxdb-auth-secret
  ingress:
    enabled: true
    hostname: ""
  env:
  - name:  INFLUXDB_DB
    value: "telegraf"
  initScripts:
    enabled: false
