---
kafka:
  cp-zookeeper:
    servers: 1
    persistence:
      enabled: true
      dataDirSize: 1Gi
      dataLogDirSize: 4Gi
  cp-kafka:
    brokers: 1
    configurationOverrides:
      "offsets.topic.replication.factor": "1"
      "default.replication.factor": "1"
      "min.insync.replicas": "1"
    persistence:
      enabled: true
      size: 32Gi
      disksPerBroker: 1
    prometheus:
      jmx:
        enabled: true
    nodeport:
      enabled: true
      servicePort: 19092
      firstListenerPort: 31090
  cp-kafka-connect:
    configurationOverrides:
      "config.storage.replication.factor": "1"
      "offset.storage.replication.factor": "1"
      "status.storage.replication.factor": "1"
  cp-control-center:
    configurationOverrides:
      "replication.factor": "1"

oauth2-proxy:
  config:
    existingSecret: kafka-oauth2-secret
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "data-kafka-cp-control-center" ]
  image:
    tag: v6.1.1
  ingress:
    enabled: true
    hosts:
    - kafka.play2kiz.com
    annotations:
      kubernetes.io/ingress.class: nginx
