apiVersion: v1
kind: Service
metadata:
  name: {{ include "extension.fullname" . }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
spec:
  type: {{ .Values.extension.service.type }}
  ports:
    - port: {{ .Values.extension.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "extension.selectorLabels" . | nindent 4 }}
