apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  # https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
  mapRoles: |
    - rolearn: {{ .Values.RoleARN }}
      username: system:node:{{ .Values.EC2PrivateDNSName }}
      groups:
      - system:bootstrappers
      - system:nodes

