apiVersion: v2
name: drone
description: Drone CI
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://github.com/drone/charts
- name: drone
  version: 0.1.7
  repository: https://charts.drone.io
  alias: server
# https://github.com/drone/charts
- name: drone-runner-kube
  version: 0.1.4
  repository: https://charts.drone.io
  alias: runner
# https://github.com/drone/charts
- name: drone-kubernetes-secrets
  version: 0.1.0
  repository: https://charts.drone.io
  alias: secrets
