---
namespace: data-influxdb

blue:
  persistence:
    enabled: false
  ingress:
    enabled: true
    hostname: influxdb.storage.k9etool.io
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - icloud-kage-prod-worker-1
  initScripts:
    enabled: true
