---
apiVersion: v2
name: data-docker
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://github.com/helm/charts/tree/master/stable/docker-registry
- name: docker-registry
  version: 1.9.4
  repository: https://charts.helm.sh/stable/
  alias: registry
