---
host: ""

registry:
  fullnameOverride: registry
  podAnnotations:
    co.elastic.logs/enabled: "true"
    co.elastic.logs/format: json
    co.elastic.logs/json.add_error_key: "true"
    co.elastic.logs/json.keys_under_root: "true"
    co.elastic.logs/json.message_key: msg
    co.elastic.logs/fileset.stdout: access
    co.elastic.logs/fileset.stderr: error
  storage: s3
  secrets:
    s3:
      accessKey: ""
      secretKey: ""
  s3:
    region: ""
    regionEndpoint: ""
    bucket: ""
    encrypt: true
    secure:  true
  configData:
    version: 0.1
    log:
      accesslog:
        disabled: true
      level: warn
      formatter: json
      fields:
        service: registry
        environment: ops
    storage:
      cache:
        blobdescriptor: inmemory

oauth2-proxy:
  fullnameOverride: oauth2-proxy
  config:
    existingSecret: docker-registry-web-oauth2-secret
    # https://oauth2-proxy.github.io/oauth2-proxy/configuration#config-file
    # https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "http://registry-web.data-docker.svc.cluster.local:8080" ]
      provider = "github"
  image:
    tag: v6.1.1
  extraEnv:
  - name:  OAUTH2_PROXY_GITHUB_ORG
    value: ""
  service:
    port: 4180
  podAnnotations:
    co\.elastic\.logs/enabled: "true"
    co\.elastic\.logs/fileset\.stdout: access
    co\.elastic\.logs/fileset\.stderr: error
    co\.elastic\.logs/exclude_lines: '[ "GET - \"/ping\"" ]'
