dex:
  config:
    issuer: https://dex.ghilbut.net/dex
    storage:
      type: memory
    connectors:
    - type: github
      id:   github
      name: Github
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: "https://dex.ghilbut.net/dex/callback"
        orgs:
        - name: tesseledger
    enablePasswordDB: true

  envFrom:
  - secretRef:
      name: github-client

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
    - host: dex.ghilbut.net
      paths:
      - path: /
    tls:
    - hosts:
      - dex.ghilbut.net
      secretName: dex-tls
