---
namespace: data-influxdb

blue:
  persistence:
    enabled: false
  ingress:
    enabled: true
    hostname: influxdb.storage.k9etool.io
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - icloud-kage-prod-worker-1
  initScripts:
    enabled: true

telegraf-ds:
  config:
    agent:
      interval: "10s"
      round_interval: true
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: "0s"
      flush_interval: "10s"
      flush_jitter: "0s"
      precision: ""
      debug: false
      quiet: false
      logfile: ""
      hostname: "$HOSTNAME"
      omit_hostname: false
    outputs:
    - influxdb:
        urls:
        - http://data-influxdb-blue.data-influxdb:8086/
        database: "telegraf"
        retention_policy: ""
        timeout: "5s"
        username: ""
        password: ""
        user_agent: "telegraf"
        insecure_skip_verify: false
    monitor_self: true
