---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: data-kafka-cp-control-center
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: data-kafka-cp-control-center
          servicePort: 9021
  tls: []
