apiVersion: v2
name: keycloak
description: A Helm chart for Keycloak
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://github.com/bitnami/charts/
- name: keycloak
  version: 2.3.0
  repository: https://charts.bitnami.com/bitnami/

