apiVersion: v2
name: keycloak
description: A Helm chart for Keycloak
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://github.com/codecentric/helm-charts
- name: keycloak
  version: 10.1.0
  repository: https://codecentric.github.io/helm-charts/

