keycloak:
  ingress:
    enabled: true
    hostname: keycloak.ghilbut.net
    path: /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    tls: true