dex:
  config:
    issuer: https://dex.ghilbut.net/dex
    storage:
      type: sqlite3
      config:
        file: examples/dex.db 
    connectors:
    - type: github
      id:   github
      name: Github
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: "https://dex.ghilbut.net/dex/callback"
        orgs:
       - name: tesseledger
    enablePasswordDB: true

  envFrom:
  - secretRef:
      name: github-client

  ingress:
    enable: true
    annotations:
      cert-manager.io/cluster-issuer: acme
    hosts:
    - host: dex.ghilbut.net
      paths:
      - path: /
    tls:
    - hosts:
      - dex.ghilbut.net
      secretName: dex-tls
