dex:
  config:
    issuer: https://dex.ghilbut.net
    storage: memory
    enablePasswordDB: true

    envFrom:
    - secretRef:
        name: github-client

    connectors:
    - type: github
      id: github
      name: Github
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.ghilbut.net/dex/callback
        orgs:
        - tesseledger

  ingress:
    enable: true
    annotations:
      cert-manager.io/cluster-issuer: acme
    hosts:
    - host: dex.ghilbut.net
      paths:
      - path: /
    tls:
    - hosts:
      - dex.ghilbut.net
      secretName: dex-tls
